apiVersion: v1
kind: Service
metadata:
  name: task-app-service
spec:
  selector:
    app: task-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 # The port your Java app listens on
      nodePort: 30080 # Accessible at host_ip:30080