# .github/workflows/main.yml
name: Java Task Manager API CI/CD  # <--- ERROR IS HERE (Line 2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ... the rest of the file continues below ...